/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consumer.loan.assistant.project;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author vaibh
 */
public class CLAPMain extends javax.swing.JFrame {
    boolean monthPayment;

    /**
     * Creates new form CLAPMain
     */
    public CLAPMain() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Loan Assistant");
        setResizable(false);
        second.setVisible(false);
        MonthlyPay.setBackground(Color.YELLOW);
        MonthlyPay.setEditable(false);
        monthPayment=true;
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                 int ans=JOptionPane.showConfirmDialog(null,"Your realy want to Close the App","Conformation",JOptionPane.YES_NO_OPTION);
                    if(ans==JOptionPane.YES_OPTION)
                    {
                      System.exit(0);
                     }
            }
        });
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        temp1 = new javax.swing.JLabel();
        temp2 = new javax.swing.JLabel();
        temp3 = new javax.swing.JLabel();
        temp4 = new javax.swing.JLabel();
        computeMonthly = new javax.swing.JButton();
        newLoadAnalysis = new javax.swing.JButton();
        loanBalance = new javax.swing.JTextField();
        interestRate = new javax.swing.JTextField();
        NoofPayment = new javax.swing.JTextField();
        MonthlyPay = new javax.swing.JTextField();
        first = new javax.swing.JButton();
        second = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        temp1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        temp1.setText("Loan Balance ");

        temp2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        temp2.setText("Interest Rate");

        temp3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        temp3.setText("Number Of Payments");

        temp4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        temp4.setText("Monthly Payments");

        computeMonthly.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        computeMonthly.setText("Compute Monthly Payment");
        computeMonthly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeMonthlyActionPerformed(evt);
            }
        });

        newLoadAnalysis.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newLoadAnalysis.setText("New Loan Analysis ");
        newLoadAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newLoadAnalysisActionPerformed(evt);
            }
        });

        loanBalance.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        loanBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanBalanceActionPerformed(evt);
            }
        });
        loanBalance.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                loanBalancePropertyChange(evt);
            }
        });

        interestRate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        NoofPayment.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        MonthlyPay.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        first.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        first.setText("X");
        first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstActionPerformed(evt);
            }
        });

        second.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        second.setText("X");
        second.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondActionPerformed(evt);
            }
        });

        TextArea.setColumns(20);
        TextArea.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Loan Analysis");

        exit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(temp4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(temp3)
                            .addComponent(temp2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(temp1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loanBalance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(interestRate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NoofPayment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MonthlyPay, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(second, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(first, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(computeMonthly, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(newLoadAnalysis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temp1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temp2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(interestRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temp3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoofPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(first, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temp4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthlyPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(second))
                .addGap(18, 18, 18)
                .addComponent(computeMonthly, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newLoadAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void computeMonthlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeMonthlyActionPerformed
        // TODO add your handling code here:
        
                double balance, interest, payment;
        int months;
        double monthlyInterest, multiplier;
        balance =  Double.valueOf(loanBalance.getText()).doubleValue();
        interest = Double.valueOf(interestRate.getText()).doubleValue();
        monthlyInterest = interest / 1200;
        if (monthPayment)
        {
        // Compute loan payment
            months =
            Integer.valueOf(NoofPayment.getText()).intValue();
            multiplier = Math.pow(1 + monthlyInterest, months);
            payment = balance * monthlyInterest * multiplier / (multiplier - 1);
            MonthlyPay.setText(new DecimalFormat("0.00").format(payment));
        }
        else
        {
        // Compute number of payments
            payment =
            Double.valueOf(MonthlyPay.getText()).doubleValue();
            months = (int)((Math.log(payment) - Math.log(payment - balance * monthlyInterest))
            / Math.log(1 + monthlyInterest));
            NoofPayment.setText(String.valueOf(months));
        }
            
         
            payment=Double.valueOf(MonthlyPay.getText()).doubleValue();
            // show analysis
            TextArea.setText("Loan Balance: $" + new
            DecimalFormat("0.00").format(balance));
            TextArea.append("\n" + "Interest Rate: " + new
            DecimalFormat("0.00").format(interest) + "%");
            // process all but last payment
           double  loanBal = balance;
            for (int paymentNumber = 1; paymentNumber <= months - 1; paymentNumber++)
            {
            loanBal += loanBal * monthlyInterest - payment;
            }
            // find final payment
            double finalPayment = loanBal;
            if (finalPayment > payment)
            {
            // apply one more payment
            loanBal += loanBal * monthlyInterest - payment;
            finalPayment = loanBal;
            months++;
           
            MonthlyPay.setText(String.valueOf(months));
            }
            TextArea.append("\n\n" + String.valueOf(months - 1) + " Payments of $" + new
            DecimalFormat("0.00").format(payment));
            TextArea.append("\n" + "Final Payment of: $" + new
            DecimalFormat("0.00").format(finalPayment));
            TextArea.append("\n" + "Total Payments: $" + new
            DecimalFormat("0.00").format((months - 1) * payment + finalPayment));
            TextArea.append("\n" + "Interest Paid $" + new
            DecimalFormat("0.00").format((months - 1) * payment + finalPayment - balance));
    }//GEN-LAST:event_computeMonthlyActionPerformed

    private void loanBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanBalanceActionPerformed

    private void newLoadAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newLoadAnalysisActionPerformed
        // TODO add your handling code here:
      
        
        TextArea.setText("");
        MonthlyPay.setText("");
        NoofPayment.setText("");
       
    }//GEN-LAST:event_newLoadAnalysisActionPerformed

    private void loanBalancePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_loanBalancePropertyChange
        // TODO add your handling code here:
//        try{
//      String text=  loanBalance.getText();
//      double balance=Double.parseDouble(text);
//        }catch(Exception e)
//        {
//            JOptionPane.showMessageDialog(null,"You can only put numbers only");
//            loanBalance.setText("");
//        }
    }//GEN-LAST:event_loanBalancePropertyChange

    private void firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstActionPerformed
        // TODO add your handling code here:
        first.setVisible(false);
        second.setVisible(true);
        MonthlyPay.setText("");
        NoofPayment.setText("");
        MonthlyPay.setEditable(true);
        MonthlyPay.setBackground(Color.WHITE);
        NoofPayment.setEditable(false);
        NoofPayment.setBackground(Color.YELLOW);
        monthPayment=false;
                TextArea.setText("");

        
    }//GEN-LAST:event_firstActionPerformed

    private void secondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondActionPerformed
        // TODO add your handling code here:
        first.setVisible(true);
        second.setVisible(false);
           MonthlyPay.setText("");
        NoofPayment.setText("");
        TextArea.setText("");
        NoofPayment.setEditable(true);
        MonthlyPay.setEditable(false);
        monthPayment=true;
        NoofPayment.setBackground(Color.WHITE);
        MonthlyPay.setBackground(Color.YELLOW);
    }//GEN-LAST:event_secondActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CLAPMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CLAPMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CLAPMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CLAPMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CLAPMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MonthlyPay;
    private javax.swing.JTextField NoofPayment;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JButton computeMonthly;
    private javax.swing.JButton exit;
    private javax.swing.JButton first;
    private javax.swing.JTextField interestRate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField loanBalance;
    private javax.swing.JButton newLoadAnalysis;
    private javax.swing.JButton second;
    private javax.swing.JLabel temp1;
    private javax.swing.JLabel temp2;
    private javax.swing.JLabel temp3;
    private javax.swing.JLabel temp4;
    // End of variables declaration//GEN-END:variables
}
